name: Terraform Checks

on:
  push:
    branches: [ main ]  # Adjust branch to trigger on

jobs:
  terraform_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        run: |
         terraform init
         terraform fmt -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Install TFLint
        run: |
          curl -sfL https://releases.hashicorp.com/tflint/v/tflint_linux_amd64.zip -o tflint.zip
          unzip tflint.zip -d bin
          rm tflint.zip
          chmod +x bin/tflint
        working-directory: ${{ github.workspace }}

      - name: Verify TFLint Installation
        run: bin/tflint --version
        working-directory: ${{ github.workspace }}
