name: Terraform Checks

on:
  push:
    branches: [ main ]  # Adjust branch to trigger on

jobs:
  terraform_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        run: terraform fmt -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Install TFLint
        run: curl -sfL https://releases.hashicorp.com/tflint/v${{ env.TFLINT_VERSION }}/tflint_linux_amd64.zip -o tflint.zip && unzip tflint.zip && mv tflint bin/tflint

      - name: Run TFLint
        env:
          TFLINT_CONFIG: path/to/your/tflint.config  # Optional, path to your TFLint config file
        run: bin/tflint

